# Generated by Django 5.2.6 on 2025-10-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('special', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
