# Generated by Django 5.2.6 on 2025-10-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_bazar_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pos',
            field=models.IntegerField(unique=True),
        ),
    ]
