# Generated by Django 5.2.6 on 2025-10-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_bazar_App', '0002_alter_item_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pos',
            field=models.IntegerField(),
        ),
    ]
