# Generated by Django 5.2.6 on 2025-10-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_bazar_App', '0003_alter_item_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
