# Generated by Django 5.2.6 on 2025-10-09 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_bazar_App', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_as_admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_As_Admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
