# Generated by Django 5.2.6 on 2025-10-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_bazar_App', '0004_admin_user_as_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='admin',
        ),
    ]
