# Generated by Django 5.2.6 on 2025-10-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_bazar_App', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
